# Generated by Django 4.1.2 on 2022-10-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('FormID', models.AutoField(primary_key=True, serialize=False)),
                ('FormName', models.CharField(max_length=500)),
            ],
        ),
    ]
